### ISSUE TITLE
当婊子还要立牌坊?

### ISSUE THREAD

**Issue by buffge** [zorlan/skycaiji#4]
既然已经选择了开源 还弄乱代码格式是什么意思?不想让人看? IDE一键格式化的事.

**Comment by zorlan** [comment]
呵呵，php_strip_whitespace 是php的功能，压缩代码而已，ctrl+i 不就可以看了吗？大佬，你这么厉害，还是不要用我这个垃圾程序了，呵呵呵

**Comment by zorlan** [comment]
原来你也是做爬虫的啊！呵呵，难怪这么气急败坏

**Comment by ixixixe2** [comment]
开源协议应该加一个，弱智不能用

**Comment by GitHubAFeng** [comment]
哈哈，谢谢题主让我笑了一下

**Comment by dphong** [comment]
> 既然已经选择了开源 还弄乱代码格式是什么意思?不想让人看? IDE一键格式化的事.

哈哈哈哈，题主真逗

**Comment by qinmenghua** [comment]
这点智商，还是别用了。污了眼睛

**Comment by buffge** [comment]
> 这点智商，还是别用了。污了眼睛

脑子是个好东西,可惜你没有:)

**Comment by qinmenghua** [comment]
> > 这点智商，还是别用了。污了眼睛
> 
> 脑子是个好东西,可惜你没有:)

笑死，到底是僵尸吃了你的脑子，还是里面本来就是豆腐渣
1、你可以选择不用。
2、有本事你可以自己看
3、开发者没义务保证你的可读性。
4、哪来的天生优越感，有脾气自己开发去。

**Comment by buffge** [comment]
> > > 这点智商，还是别用了。污了眼睛
> > 
> > 
> > 脑子是个好东西,可惜你没有:)
> 
> 笑死，到底是僵尸吃了你的脑子，还是里面本来就是豆腐渣
> 1、你可以选择不用。
> 2、有本事你可以自己看
> 3、开发者没义务保证你的可读性。
> 4、哪来的天生优越感，有脾气自己开发去。

1. 我一直都没用
2. 垃圾代码不想看
3. 垃圾开发者开发垃圾东西,这种垃圾确实没有义务保证别人的可读性
4. 谁告诉你我天生优越感? 我自己开发的爬虫很多
